/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atrain;

import javax.swing.JLabel;

/**
 *
 * @author Acer
 */
public class halamanNota extends javax.swing.JFrame {
    private halamanKereta halamanKereta;

    /**
     * Creates new form halamanNota
     */
    
    public void tampilkanNota(halamanKereta halamanKereta){
        String jenisKereta = halamanKereta.getJenisKereta().getSelectedItem().toString();
        notaKereta.setText(jenisKereta);
        
        String jumlahTiket = halamanKereta.getJumlahTiket().getText();
        notaTiket.setText(jumlahTiket);
        
        String jumlahLansia = halamanKereta.getJumlahLansia().getText();
        notaLansia.setText(jumlahLansia);
        
        String jumlahAnak = halamanKereta.getJumlahAnak().getText();
        notaAnak.setText(jumlahAnak);
        
        if (halamanKereta.getWifi().isSelected()){
            notaWifi.setVisible(true);
        }
        else{
            notaWifi.setVisible(false);
        }
        
        if (halamanKereta.getMakan().isSelected()){
            notaMakan.setVisible(true);
        }
        else{
            notaMakan.setVisible(false);
        }
        
        if (halamanKereta.getBagasi().isSelected()){
            notaBagasi.setVisible(true);
        }
        else {
            notaBagasi.setVisible(false);
        }
        
        String kode = "VIPRIDE";
        String promo = halamanKereta.getPromo().getText();
        if (promo.equals(kode)){
            notaPromo.setVisible(true);
        }
        else {
            notaPromo.setVisible(false);
        }
        
//        String tiketReguler = halamanKereta.getJumlahReguler();
        notaReguler.setText(halamanKereta.getJumlahReguler());
        
//        String diskonLansiaNota = (halamanKereta.getDiskonLansia());

//        String diskonAnakNota = halamanKereta.getDiskonAnak();
//        notaDiskonAnak.setText(diskonAnakNota);
//        
//        String notaTotalDiskonAwal = halamanKereta.getDiskonAwal();
//        notaDiskon.setText(notaTotalDiskonAwal);
//        
//        String notaTotalDiskonTiket = halamanKereta.getTotalDiskonTiket();
//        notaPotongan.setText(notaTotalDiskonTiket);
//        
//        String notaTotalSeluruhHarga = halamanKereta.getTotalHarga();
//        notaHarga.setText(notaTotalSeluruhHarga);
//        
//        String notaTotalBiaya = halamanKereta.getTotalBiaya();
//        notaTotal.setText(notaTotalBiaya);
    }
    
    public void updateDiskonLansia(double totalDiskonLansia){
        String lansia = Double.toString(totalDiskonLansia);
        System.out.println("Method Diskon Lansia" + lansia);
        notaDiskonLansia.setText(lansia);
    }
    public halamanNota() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        notaWifi = new javax.swing.JLabel();
        notaMakan = new javax.swing.JLabel();
        notaBagasi = new javax.swing.JLabel();
        notaPromo = new javax.swing.JLabel();
        notaLayanan = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        notaKereta = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        notaReguler = new javax.swing.JLabel();
        notaLansia = new javax.swing.JLabel();
        notaDiskonLansia = new javax.swing.JLabel();
        notaAnak = new javax.swing.JLabel();
        notaDiskonAnak = new javax.swing.JLabel();
        notaTiket = new javax.swing.JLabel();
        notaDiskon = new javax.swing.JLabel();
        notaPotongan = new javax.swing.JLabel();
        notaHarga = new javax.swing.JLabel();
        notaTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel1.setText("Nota Pembayaran Tiket Kereta");

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Kereta");

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah Keseluruhan Tiket");

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel5.setText("Diskon Lansia ");

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah Tiket Reguler");

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel7.setText("Jumlah Tiket Anak-Anak");

        jLabel8.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel8.setText("Jumlah Tiket Lansia ");

        jLabel9.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel9.setText("Diskon Anak-Anak");

        jLabel10.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel10.setText("--------------------------------------------------------------------------------------");

        jLabel11.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel11.setText("--------------------------------------------------------------------------------------");

        jLabel12.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel12.setText("--------------------------------------------------------------------------------------");

        notaWifi.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaWifi.setText("Fasilitas Wi-fi..........................................................................Rp20.000/tiket");

        notaMakan.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaMakan.setText("Fasilitas Makan.......................................................................Rp50.000/tiket");

        notaBagasi.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaBagasi.setText("Fasilitas Bagasi Tambahan.....................................................Rp50.000/tiket");

        notaPromo.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaPromo.setText("Kode Promo: VIPRIDE                                                                            -20%");

        notaLayanan.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaLayanan.setText("Biaya Layanan Rp15.000                                                            Pajak +10%");

        jLabel18.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel18.setText("Diskon Tiket");

        jLabel19.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel19.setText("--------------------------------------------------------------------------------------");

        jLabel20.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel20.setText("Total Harga");

        jLabel21.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel21.setText("Total yang Harus Dibayar");

        notaKereta.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaKereta.setText("Jenis Kereta");
        notaKereta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaKeretaComponentShown(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel22.setText("Total Potongan Harga");

        notaReguler.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaReguler.setText("notaReguler");
        notaReguler.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaRegulerComponentShown(evt);
            }
        });

        notaLansia.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaLansia.setText("notaLansia");
        notaLansia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaLansiaComponentShown(evt);
            }
        });

        notaDiskonLansia.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaDiskonLansia.setText("-Rp5000");
        notaDiskonLansia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaDiskonLansiaComponentShown(evt);
            }
        });

        notaAnak.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaAnak.setText("notaAnak");
        notaAnak.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaAnakComponentShown(evt);
            }
        });

        notaDiskonAnak.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaDiskonAnak.setText("-Rp7000");
        notaDiskonAnak.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaDiskonAnakComponentShown(evt);
            }
        });

        notaTiket.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaTiket.setText("notaTiket");
        notaTiket.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaTiketComponentShown(evt);
            }
        });

        notaDiskon.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaDiskon.setText("-Rp11000");
        notaDiskon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                notaDiskonComponentShown(evt);
            }
        });

        notaPotongan.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaPotongan.setText("-Rp30000");

        notaHarga.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaHarga.setText("Rp780000");

        notaTotal.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        notaTotal.setText("Rp750000");

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Futura Md BT", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Kembali");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaTotal))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notaDiskonAnak, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(notaTiket, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(notaDiskon, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(notaReguler, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaKereta))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notaLansia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notaAnak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaDiskonLansia))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaHarga))
                            .addComponent(notaMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notaWifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notaBagasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notaPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notaLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaPotongan))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(notaKereta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(notaReguler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(notaLansia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(notaDiskonLansia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(notaAnak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(notaDiskonAnak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(notaTiket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(notaDiskon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notaWifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notaMakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notaBagasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notaPromo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notaLayanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(notaHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(notaPotongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(notaTotal))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notaKeretaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaKeretaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaKeretaComponentShown

    private void notaRegulerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaRegulerComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaRegulerComponentShown

    private void notaLansiaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaLansiaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaLansiaComponentShown

    private void notaDiskonLansiaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaDiskonLansiaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaDiskonLansiaComponentShown

    private void notaAnakComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaAnakComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaAnakComponentShown

    private void notaDiskonAnakComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaDiskonAnakComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaDiskonAnakComponentShown

    private void notaTiketComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaTiketComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaTiketComponentShown

    private void notaDiskonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notaDiskonComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_notaDiskonComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        halamanKereta halamanKereta = new halamanKereta();
        halamanKereta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel notaAnak;
    private javax.swing.JLabel notaBagasi;
    private javax.swing.JLabel notaDiskon;
    private javax.swing.JLabel notaDiskonAnak;
    private javax.swing.JLabel notaDiskonLansia;
    private javax.swing.JLabel notaHarga;
    private javax.swing.JLabel notaKereta;
    private javax.swing.JLabel notaLansia;
    private javax.swing.JLabel notaLayanan;
    private javax.swing.JLabel notaMakan;
    private javax.swing.JLabel notaPotongan;
    private javax.swing.JLabel notaPromo;
    private javax.swing.JLabel notaReguler;
    private javax.swing.JLabel notaTiket;
    private javax.swing.JLabel notaTotal;
    private javax.swing.JLabel notaWifi;
    // End of variables declaration//GEN-END:variables
}
